name: 'snowflake_lab_project'
version: '1.0.0'
config-version: 2
profile: 'default'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]
models:
  snowflake_lab_project:
    +materialized: view
    staging:
      +materialized: table
      +schema: RAW_STAGING # Destino para staging
    marts:
      +schema: ANALYTICS # Destino para marts