version: 2

sources:
  - name: raw_customer_data # Grupo lógico de fuentes
    database: LAB_DB        # Base de datos origen en Snowflake
    schema: BRONZE          # Schema origen

    tables:
      - name: CUSTOMERS_RAW # Tabla bronza cargada desde customers.csv
        description: "Tabla fuente de clientes en LAB_DB.BRONZE.CUSTOMERS_RAW."
        columns:
          - name: customer_id
            description: "Identificador del cliente en la capa BRONZE."
            tests:
              - not_null
              - unique
